#!/bin/bash
#clear
export covestorlog="covestor.output"  #search history generated by covester.sh |tee output
export thelionlog="thelion.output"    #search history generated by thelion.sh.sh |tee output

>tmp
export price=`curl "http://finance.yahoo.com/q?s=$1" |egrep -o 'yfs_l84_[a-z]+">[0-9]+.[0-9]+' |cut -d'>' -f2`
export time=`date +%m/%d/%Y`
echo $1:$price $time

curl "http://www.finviz.com/quote.ashx?t=$1" > tmp
cat tmp|grep center |grep '_blank' |cut -d'>' -f5 |cut -d'<' -f1
cat tmp|grep center |grep fullview-links |grep tab-link |cut -d'>' -f4,6,8 |sed 's/<\/a/ /g'
echo "FA color-coded=============================="
for key in 'Market Cap' 'P/E' 'Forward P/E' 'P/C' 'P/FCF' 'P/B' 'Debt/Eq' 'Current Ratio' 'ROA' 'ROE' 'EPS next 5Y' 'Dividend %'
do
	color=`cat tmp |grep ">$key<" |egrep -o "color:#[0-9a]+" |cut -d':' -f2`
	val=`cat tmp |grep ">$key<" |egrep -o ">[0-9]+.[0-9]+<|>[0-9]+.[0-9]+B<|>[0-9]+.[0-9]+M<|>[0-9]+.[0-9]+%<" |sed -e 's/>//g' -e 's/<//g'`
	if [ "$color" == '#aa0000' ]; then 
		echo -e "$key:\t\t\e[00;31m$val\e[00m" 
	elif [ "$color" == '#008800' ]; then 
		echo -e "$key:\t\t\e[00;32m$val\e[00m" 
	else 
		echo -e "$key:\t\t$val"
    fi
done
echo "================================"
#gurufocus biz predicability
export predstar=`curl "http://www.gurufocus.com/gurutrades/$1" |grep "Business Predictability" |egrep -o "[0-9].[0-9]-Star<|[0-9]-Star<"  |cut -d'-' -f1`
echo -e "Predictability:\t" $predstar
#MSN StockScouter
curl "http://moneycentral.msn.com/investor/StockRating/srsmain.asp?Symbol=$1" > tmp
#export MSNStockScouter=`cat tmp |egrep  "SRS[0-9]" |cut -d"." -f1|cut -d"/" -f2 |cut -c 4-5`
export MSNStockScouter=`cat tmp |egrep  -o "StockScouter Rating: [0-9]{1,2}" |cut -d':' -f2 |sed 's/ //g'`
export Fudamental=`cat tmp |grep -i Fundamental |grep -o ">[A-F]<" |cut -c 2`
export Ownership=`cat tmp |grep -i Ownership |grep -o ">[A-F]<" |cut -c 2`
export Valuation=`cat tmp |grep -i Valuation |grep -o ">[A-F]<" |cut -c 2`
export Technical=`cat tmp |grep -i Technical |grep -o ">[A-F]<" |cut -c 2`
echo -e "MSN Rating:\t"$MSNStockScouter

#Crammer's MadMoney comments
export madmoneyurl="http://madmoney.thestreet.com/07/index.cfm?page=lookup"
export madmoneylookup="symbol=$1"
curl -d $madmoneylookup $madmoneyurl |egrep -m 1  ">[0-9]{2}/[0-9]{2}/200?" -A 20 >tmp1$$ #care the latest one
export maddate=`cat tmp1$$ |egrep -o "[0-9]{2}/[0-9]{2}/20[0-9][0-9]"`
export madbuysell=`cat tmp1$$ |egrep -o "[1-5]\.gif"|sed 's/.gif//g' |sed 's/5/SB/g'|sed 's/4/B/g'|sed 's/3/H/g'|sed 's/2/S/g'| sed 's/1/SS/g'`
export madvalue=`cat tmp1$$ |egrep -o "[0-9]+\.[0-9]+"|head -n 1`
export madchange=`cat tmp1$$ |egrep -o "\+ [0-9]+\.[0-9]+%|\- [0-9]+\.[0-9]+%"|tail -n 1`
echo -e "Crammer:\t"$maddate $madbuysell $madvalue $madchange

#w.r.t S&P 50MA
curl "http://download.finance.yahoo.com/d/quotes.csv?s=$1,SPY&f=m8" |cat -v |sed -e 's/%//g' -e 's/ //g' -e 's/\^M//g' |tr '\n' ' ' |awk '{print  "50MA vs. S&P:\t" $1" vs. "$2}'

#stoxline rating
export stoxline=`curl "http://www.stoxline.com/quote.php?symbol=BBW" |grep margin-bottom |grep "http://www.stoxline.com/pics/[0-9]s.png" |egrep  -o '[0-9]s.png' |sed 's/s.png/ stars/g'`
echo -e "Stoxline:\t"$stoxline

#MotleyFool's rating
export star=`curl "http://caps.fool.com/Ticker/$1.aspx" |grep -A 2 "CAPS Rating" |egrep -o "[0-9] out of 5" |awk '{print $1}'`
echo -e "MotelyFool:\t"$star

#Trend Spotter
trenspotter=`curl "http://www.stockta.com/cgi-bin/opinion.pl?symb=$1&num1=4&mode=stock"|sed 's/TR/\n/g' |grep "Trend Spotter"  |egrep -o ">Buy<|>Sell<|>Hold<" |sed -e 's/>//g' -e 's/<//g'`
echo -e "Trend Spotter:\t"$trenspotter

#Stock Picker rating
upper=`echo $1|tr a-z A-Z`
curl "http://www.stockpickr.com/symbol/$upper" |egrep "ratings" |grep "summary" |cut -d'>' -f4 |cut -d'<' -f1 |while read line
do
    echo -e "Stockpickr:\t"$line
done

#Social Picker's rating; slow and comments out
curl "http://www.socialpicks.com/stock/$upper/sentiment" > tmp
socialpicker=`cat tmp |egrep -B 3 "\([0-9]+ ratings\)" |head -n 1 |cut -d'>' -f3- |cut -d'<' -f1`
socialstar=`cat tmp |egrep -o "graphic_star_big.gif" |wc -l`
socialhalfstar=`cat tmp |egrep -o "graphic_star_big_half.gif" |wc -l`
socialstarnum=`echo "scale=1;$socialstar + $socialhalfstar/2" |bc`
echo -e "SocialPicker:\t"$socialpicker" "$socialstarnum" stars"

#GStock
export lower=`echo $1|tr A-Z a-z`
curl http://www.gstock.com/quote/$lower.html |egrep -o "BUY|SELL"  |head -n 1 |while read line
do
    echo -e "GStock ALert:\t" $line
done

#guru focus fair value
curl "http://www.gurufocus.com/gurutrades/$1" |grep "Fair Value Votes for" |egrep -o 'call">\$[0-9]+.[0-9]+|call">\$[0-9]+' |cut -d'>' -f2 |while read fairvalue
do
echo -e "GuruFairValue:\t" $fairvalue
done

#TA pattern
export signal=`curl "http://www.americanbulls.com/SignalPage.aspx?lang=en&Ticker=$1" |grep "MainContent_LastSignal"|egrep -o ">[A-Z ]+</font>" |cut -d'<' -f1|cut -d'>' -f2`
export pattern=`curl "http://www.americanbulls.com/SignalPage.aspx?lang=en&Ticker=$1" |grep "MainContent_LastPattern"  |tail -n 1 | cut -d'>' -f3- |cut -d'<' -f1`
echo -e "USBull Signal\t" $signal 
echo -e "USBull Pattern\t" $pattern

found=$(grep -w $1 $covestorlog)
if [[ $? -eq 0 ]]; then
	echo "Covestor Top Manager Recent Transactions=================="
	echo "Stock Action Price Date Trade/Mon Return Manager Portfolio" |awk  '{printf "%-10s %-10s %-10s %-10s %-10s %-10s %-30s %-20s\n", $1,$2,$3,$4,$5,$6,$7,$8}'
	grep -w $1 $covestorlog
fi 

found=$(curl "http://stocks.covestor.com/$lower" |egrep -B 1000 -i "in the same sector" |egrep -A 1 'a href="http://covestor.com/[a-zA-Z]+|value positive|value negative' |egrep -o 'a href="http://covestor.com/[a-zA-Z\-]+/[a-zA-Z\-]+|[0-9]+.[0-9]+|-[0-9]+.[0-9]+' |sed 's/a href=\"http:\/\/covestor.com//g' |tr '\n' ' ' |sed 's/ \//\n/g' |sed 's/^\///g' |sed 's/\// /g' |awk '{ printf "%-40s%-40s%10s%10s%\n", $1, $2,$3,$4 }')
if [[ $? -eq 0 ]]; then
	echo "Covestor Top Manager Current Holdings====================="
	echo "Manager Portfolio Sharp% Gain"|awk '{ printf "%-40s%-40s%10s%10s%\n", $1, $2,$3,$4 }'
	curl "http://stocks.covestor.com/$lower" |egrep -B 1000 -i "in the same sector" |egrep -A 1 'a href="http://covestor.com/[a-zA-Z]+|value positive|value negative' |egrep -o 'a href="http://covestor.com/[a-zA-Z\-]+/[a-zA-Z\-]+|[0-9]+.[0-9]+|-[0-9]+.[0-9]+' |sed 's/a href=\"http:\/\/covestor.com//g' |tr '\n' ' ' |sed 's/ \//\n/g' |sed 's/^\///g' |sed 's/\// /g' |awk '{ printf "%-40s%-40s%10s%10s%\n", $1, $2,$3,$4 }'
fi

found=$(grep -w $1 $thelionlog)
if [[ $? -eq 0 ]]; then
	echo "TheLion Top Manager Recent Transactions==================="
	echo "User Stock Status Action Buydate Dummy Selldate dummy Buyprice Sellprice Gain%" |awk '{printf "%-15s %-5s %-10s %-7s %-10s %-10s %-10s %-10s %-10s\n",$1,$2,$3,$4,$5,$7,$9,$10,$11}'
	grep -w $1 $thelionlog
fi

echo "Radar Screen----------------------------------------"
curl "http://www.grahaminvestor.com/screens/graham-intrinsic-value-stocks/" |egrep -o 'bc\?s=[A-Z.]+'|cut -d'=' -f2 |egrep -w "$1$" |sed "s/$1/Graham Intrinsic Value/g"
curl "http://www.grahaminvestor.com/screens/low-price-to-operating-cash-flow-ratio/" |egrep -o 'bc\?s=[A-Z.]+'|cut -d'=' -f2 |egrep -w "$1$" |sed "s/$1/Low Price to Operating CashFlow Raio/g"

curl "http://seekingalpha.com/analysis/investing-ideas/long-ideas" |egrep -o "/symbol/[a-z]+" |cut -d'/' -f3 |tr [:lower:]  [:upper:] |egrep -w "$1$" | sed "s/$1/SeekingAlphaLongIdea/g"
curl "http://seekingalpha.com/analysis/investing-ideas/short-ideas" |egrep -o "/symbol/[a-z]+" |cut -d'/' -f3 |tr [:lower:]  [:upper:] |egrep -w "$1$" |sed "s/$1/SeekingAlphaShortIdea/g"
curl "http://seekingalpha.com/analysis/investing-ideas/top-ideas" |egrep -o "/symbol/[a-z]+" |cut -d'/' -f3 |tr [:lower:]  [:upper:]  |egrep -w "$1$" |sed "s/$1/SeekingAlphaTopIdea/g"

curl "http://www.wenxuecity.com/bbs/archive.php?page=0&keyword=Long&SubID=finance&year=current" |egrep  -o -i "long [A-Za-z]+"  |grep -v term|grep -v target |grep -v bar |grep -v shadow |grep -v time |grep -v driveway |grep -v position |tr '[:lower:]' '[:upper:]' |sed 's/LONG //g' |sort |uniq |egrep -w "$1$" |sed "s/$1/DaQianLongIdea/g"

curl http://www.marketocracy.com/mds/teams |egrep -o "http://m100.marketocracy.com/[A-Za-z_]+" |while read portfolio
do
    curl "$portfolio/2portfolio/" |grep symbol |egrep -o ">[A-Z]+<" |sed -e 's/>//g' -e 's/<//g' |egrep -w "$1$" |sed "s/$1/MarketocracyTopHolding/g"
done

curl "http://www.insidercow.com/notLogin/buyByCompany.jsp?ORDER=asc&SORTBY=company_name&days=6" |egrep -o "company=[A-Z]+"|sort |uniq |cut -d'=' -f2 |egrep -w "$1$" |sed "s/$1/Insider Buy/g"

\rm -f tmp*

